  server:
     
     port: 8090
     servlet:
      
      context-path: /
      
  spring:
      mvc:
       view:
           prefix: /WEB-INF/views/
           suffix: .jsp

      datasource:
           url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
           username: root
           password: bitc5600
           driver-class-name: com.mysql.cj.jdbc.Driver

      servlet:
       multipart:
           enabled: true
           max-file-size: 1MB

